#!/usr/bin/env bash
set -euo pipefail

readonly REFRESH_SECS=60
readonly CACHE_FILE=~/.pubip.cache
readonly UPSTREAM=icanhazip.com

function update_public_ip_cache {
    echo "$(date +%s):$(curl "${UPSTREAM}" 2> /dev/null)" | tee "${CACHE_FILE}"
}

function main {
    if ! test -f "${CACHE_FILE}"; then
        echo " $(update_public_ip_cache | cut -d':' -f2)"
        exit 0
    fi

    if test $(( $(date +%s) - $(cut -d':' -f1 < "${CACHE_FILE}") )) -ge "${REFRESH_SECS}"; then
        update_public_ip_cache | cut -d':' -f2
        exit 0
    fi

    echo " $(cut -d':' -f2 < "${CACHE_FILE}")"
}

main
